#!/usr/bin/env python3

import subprocess
import tkinter as tk
from tkinter import messagebox
from pathlib import Path

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

HERE          = Path(__file__).resolve().parent
RAYTRACER     = HERE / "raytracer"
SCENE_PATH    = HERE / "_scene.txt"
OUTPUT_PPM    = HERE / "_render.ppm"
EXPOSURE_N    = 60

LIGHT_STEP    = 1.0
INITIAL_LIGHT = [0.0, 15.0, 8.0]

HOLD_INITIAL_DELAY = 400   # ms before first auto-repeat
HOLD_REPEAT_DELAY  = 80    # ms between repeats while held

# ---------------------------------------------------------------------------
# Scene definitions
# ---------------------------------------------------------------------------

SCENE_BASIC = "basic"
SCENE_SOLAR = "solar"

SHAPES_BASIC = [
    ("Red Sphere",     "sphere -3 0 0 2.5  0.85 0.15 0.10"),
    ("Green Sphere",   "sphere 4 -2 -2 2.0  0.10 0.70 0.20"),
    ("Blue Cube",      "cube -6 0 -1 1.5    0.20 0.40 0.90"),
    ("Orange Square",  "square 6 3 0 1.5    0.95 0.55 0.15"),
    ("Yellow Pyramid", "triangle -2 5 -3 2 5 -3 0 9 -1   0.90 0.80 0.20"),
]

# Solar room: fixed set of objects — panel at y=-2, furniture around it
SHAPES_SOLAR = [
    ("Floor",       "square 0 -4 0 12   0.55 0.50 0.45"),
    ("Back Wall",   "square 0  6 0 10   0.60 0.58 0.55"),
    ("Left Wall",   "square -10 1 0 10  0.62 0.60 0.58"),
    ("Right Wall",  "square  10 1 0 10  0.60 0.58 0.55"),
    ("Ceiling",     "square 0 12 0 12   0.70 0.70 0.72"),
    ("Solar Panel", "square 0 -2 2 3    0.05 0.12 0.25"),  # dark blue panel
    ("Table",       "cube  5 -2 1 1.5   0.55 0.38 0.20"),
    ("Chair",       "cube -5 -3 2 1.0   0.40 0.28 0.18"),
    ("Lamp",        "sphere 5  0 1 0.5  0.90 0.85 0.70"),
    ("Bookshelf",   "cube -8  1 -2 1.8  0.30 0.22 0.15"),
]

# Overview map markers
_OV_SHAPES_BASIC = [
    (-3,  0, 9, "#b02020"),
    ( 4, -2, 7, "#206020"),
    (-6, -1, 8, "#204080"),
    ( 6,  0, 6, "#c07010"),
    ( 0, -2, 5, "#909010"),
]

_OV_SHAPES_SOLAR = [
    ( 0,  2, 12, "#33445a", ""),
    ( 0, -2,  3, "#0d2a50", "Panel"),
    ( 5,  1,  5, "#7a5c32", ""),
    (-5,  2,  4, "#6a4828", ""),
    (-8, -2,  3, "#4a3820", ""),
]

# ---------------------------------------------------------------------------
# Palette
# ---------------------------------------------------------------------------
BG          = "#1a1a1f"
PANEL       = "#23232b"
BORDER      = "#35354a"
ACCENT      = "#f5a623"
ACCENT_HOV  = "#ffbd4f"
ACCENT_DIM  = "#a06810"
DANGER      = "#c0392b"
DANGER_HOV  = "#e74c3c"
TEXT        = "#e8e8f0"
TEXT_DIM    = "#8888aa"
TEXT_CODE   = "#b0f0c0"
CANVAS_BG   = "#0d0d12"
OVERVIEW_BG = "#12121a"
GRID_LINE   = "#1e1e2a"
LIGHT_CLR   = "#ffe066"

# Arrow/Z button colours — explicit dark bg with amber text, always readable
BTN_BG      = "#2e2e42"
BTN_FG      = ACCENT       # amber — always visible on dark bg
BTN_HOV_BG  = ACCENT
BTN_HOV_FG  = BG

FONT_UI     = ("Helvetica", 10)
FONT_BOLD   = ("Helvetica", 10, "bold")
FONT_MONO   = ("Courier",   10)
FONT_MONO_B = ("Courier",   10, "bold")
FONT_ARROW  = ("Helvetica", 16, "bold")
FONT_SMALL  = ("Helvetica",  9)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_ppm_as_photoimage(path):
    try:
        from PIL import Image, ImageTk
        return ImageTk.PhotoImage(Image.open(path))
    except ImportError:
        pass
    with open(path, "r") as f:
        tokens = f.read().split()
    assert tokens[0] == "P3"
    w, h, maxv = int(tokens[1]), int(tokens[2]), int(tokens[3])
    vals = list(map(int, tokens[4:]))
    img = tk.PhotoImage(width=w, height=h)
    for y in range(h):
        row, base = [], y * w * 3
        for x in range(w):
            r = vals[base + x*3]     * 255 // maxv
            g = vals[base + x*3 + 1] * 255 // maxv
            b = vals[base + x*3 + 2] * 255 // maxv
            row.append(f"#{r:02x}{g:02x}{b:02x}")
        img.put("{" + " ".join(row) + "}", to=(0, y))
    return img


def write_scene(light_pos, shape_lines):
    with open(SCENE_PATH, "w") as f:
        f.write("# generated by gui.py\n")
        f.write(f"light {light_pos[0]:.3f} {light_pos[1]:.3f} {light_pos[2]:.3f}\n")
        for line in shape_lines:
            f.write(line + "\n")


def run_raytracer(delete_region=None):
    cmd = [str(RAYTRACER),
           "--scene", str(SCENE_PATH),
           "--out",   str(OUTPUT_PPM),
           "--exposure-samples", str(EXPOSURE_N)]
    if delete_region:
        cmd += ["--delete-region"] + [str(v) for v in delete_region]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(
            f"raytracer failed:\nstdout:\n{result.stdout}\nstderr:\n{result.stderr}")
    stats = {}
    for line in result.stdout.splitlines():
        parts = line.split(maxsplit=1)
        if len(parts) == 2:
            stats[parts[0]] = parts[1]
    return stats


# ---------------------------------------------------------------------------
# Styled widget factories
# ---------------------------------------------------------------------------

def make_btn(parent, text, command, color=ACCENT, hover=ACCENT_HOV,
             font=FONT_BOLD, padx=14, pady=6, width=None):
    kw = dict(text=text, command=command,
              bg=color, fg=BG,
              activebackground=hover, activeforeground=BG,
              relief="flat", bd=0,
              font=font, padx=padx, pady=pady,
              cursor="hand2")
    if width:
        kw["width"] = width
    btn = tk.Button(parent, **kw)
    btn.bind("<Enter>", lambda e: btn.config(bg=hover))
    btn.bind("<Leave>", lambda e: btn.config(bg=color))
    return btn


def make_check(parent, text, variable, command=None):
    return tk.Checkbutton(
        parent, text=text, variable=variable,
        bg=PANEL, fg=TEXT,
        selectcolor=BG,
        activebackground=PANEL, activeforeground=ACCENT,
        font=FONT_UI, command=command, cursor="hand2",
        relief="flat", bd=0)


def separator(parent, orient="h", pad=6):
    if orient == "h":
        f = tk.Frame(parent, bg=BORDER, height=1)
        f.pack(fill="x", pady=pad)
    else:
        f = tk.Frame(parent, bg=BORDER, width=1)
        f.pack(fill="y", padx=pad, side="left")
    return f


# ---------------------------------------------------------------------------
# Hold-to-repeat binding
# ---------------------------------------------------------------------------

def bind_hold_repeat(btn, action_fn, root,
                     initial_delay=HOLD_INITIAL_DELAY,
                     repeat_delay=HOLD_REPEAT_DELAY):
    """Press and hold a button to keep firing action_fn repeatedly."""
    _after_id = [None]

    def _repeat():
        action_fn()
        _after_id[0] = root.after(repeat_delay, _repeat)

    def _on_press(event):
        action_fn()
        _after_id[0] = root.after(initial_delay, _repeat)

    def _on_release(event):
        if _after_id[0] is not None:
            root.after_cancel(_after_id[0])
            _after_id[0] = None

    btn.config(command=lambda: None)   # disable normal click handler
    btn.bind("<ButtonPress-1>",   _on_press)
    btn.bind("<ButtonRelease-1>", _on_release)


# ---------------------------------------------------------------------------
# Overview map canvas
# ---------------------------------------------------------------------------

OV_WORLD_MIN = -20
OV_WORLD_MAX =  20
OV_W, OV_H   = 180, 180


def _world_to_ov(wx, wz):
    px = (wx - OV_WORLD_MIN) / (OV_WORLD_MAX - OV_WORLD_MIN) * OV_W
    py = (wz - OV_WORLD_MIN) / (OV_WORLD_MAX - OV_WORLD_MIN) * OV_H
    return px, py


class OverviewCanvas(tk.Canvas):
    def __init__(self, parent, **kw):
        super().__init__(parent, width=OV_W, height=OV_H,
                         bg=OVERVIEW_BG, highlightthickness=1,
                         highlightbackground=BORDER, **kw)
        self._draw_static()

    def _draw_static(self):
        step = OV_W / 8
        for i in range(9):
            x = i * step
            self.create_line(x, 0, x, OV_H, fill=GRID_LINE, width=1)
            self.create_line(0, x, OV_W, x, fill=GRID_LINE, width=1)
        cx, cy = OV_W // 2, OV_H // 2
        self.create_line(cx, 0, cx, OV_H, fill=BORDER, width=1)
        self.create_line(0, cy, OV_W, cy, fill=BORDER, width=1)
        for txt, ax, ay in [("X+", OV_W-12, 6), ("Z+", 5, OV_H-12)]:
            self.create_text(ax, ay, text=txt, fill=TEXT_DIM, font=("Courier", 7))

    def draw_shapes(self, scene_mode, shape_vars=None):
        self.delete("shape_marker")
        if scene_mode == SCENE_BASIC:
            for i, (wx, wz, r, fill) in enumerate(_OV_SHAPES_BASIC):
                if shape_vars and not shape_vars[i].get():
                    continue
                px, py = _world_to_ov(wx, wz)
                self.create_oval(px-r, py-r, px+r, py+r,
                                 fill=fill, outline="", tags="shape_marker")
        else:
            for wx, wz, r, fill, lbl in _OV_SHAPES_SOLAR:
                px, py = _world_to_ov(wx, wz)
                self.create_oval(px-r, py-r, px+r, py+r,
                                 fill=fill, outline="", tags="shape_marker")
                if lbl == "Panel":
                    # Highlight the solar panel with amber ring
                    self.create_oval(px-r-2, py-r-2, px+r+2, py+r+2,
                                     fill="", outline=LIGHT_CLR, width=1,
                                     tags="shape_marker")
                    self.create_text(px, py, text="☀", fill=LIGHT_CLR,
                                     font=("Helvetica", 7), tags="shape_marker")

    def update_light(self, lx, ly, lz):
        self.delete("light_marker")
        px, py = _world_to_ov(lx, lz)
        ly_norm = max(0.2, min(1.0, ly / 20.0))
        halo_r  = int(12 + ly_norm * 14)
        core_r  = 5
        self.create_oval(px-halo_r, py-halo_r, px+halo_r, py+halo_r,
                         fill="", outline=LIGHT_CLR, width=2, tags="light_marker")
        mid_r = halo_r // 2
        self.create_oval(px-mid_r, py-mid_r, px+mid_r, py+mid_r,
                         fill="", outline=ACCENT_DIM, width=1, tags="light_marker")
        self.create_oval(px-core_r, py-core_r, px+core_r, py+core_r,
                         fill=LIGHT_CLR, outline=ACCENT_HOV, width=1, tags="light_marker")
        self.create_text(px, py-halo_r-7, text="☀",
                         fill=LIGHT_CLR, font=("Helvetica", 8), tags="light_marker")
        self.create_text(px, py+halo_r+8,
                         text=f"({lx:+.0f}, {lz:+.0f})",
                         fill=TEXT_DIM, font=("Courier", 7), tags="light_marker")


# ---------------------------------------------------------------------------
# Main application
# ---------------------------------------------------------------------------

class App:
    def __init__(self, root):
        self.root = root
        root.title("BVH Raytracer  —  Shadow & Exposure Analysis")
        root.configure(bg=BG)
        root.resizable(False, False)

        self.light = list(INITIAL_LIGHT)
        self.shape_vars = [tk.BooleanVar(value=True) for _ in SHAPES_BASIC]
        self.photo = None
        self._status_var = tk.StringVar(value="Ready.")
        self._scene_mode = SCENE_BASIC

        self._build_ui()
        self._render()

    # -----------------------------------------------------------------------
    # UI construction
    # -----------------------------------------------------------------------

    def _build_ui(self):
        # ── Title bar ──────────────────────────────────────────────────────
        title_bar = tk.Frame(self.root, bg=PANEL, pady=8)
        title_bar.pack(fill="x")
        tk.Label(title_bar, text="BVH RAYTRACER", bg=PANEL, fg=ACCENT,
                 font=("Helvetica", 14, "bold")).pack(side="left", padx=14)
        tk.Label(title_bar, text="shadow · exposure · spatial analysis",
                 bg=PANEL, fg=TEXT_DIM, font=FONT_SMALL).pack(side="left")

        # ── Scene switcher ─────────────────────────────────────────────────
        scene_bar = tk.Frame(self.root, bg=PANEL, padx=10, pady=6)
        scene_bar.pack(fill="x", pady=(1, 0))
        tk.Label(scene_bar, text="SCENE:", bg=PANEL, fg=TEXT_DIM,
                 font=("Helvetica", 8, "bold")).pack(side="left", padx=(0, 8))

        self._btn_basic = tk.Button(
            scene_bar, text="🔷  Basic Shapes",
            bg=ACCENT, fg=BG,
            activebackground=ACCENT_HOV, activeforeground=BG,
            relief="flat", bd=0, font=FONT_BOLD,
            padx=14, pady=5, cursor="hand2",
            command=lambda: self._switch_scene(SCENE_BASIC))
        self._btn_basic.pack(side="left", padx=(0, 6))

        self._btn_solar = tk.Button(
            scene_bar, text="☀  Solar Room",
            bg=BTN_BG, fg=BTN_FG,
            activebackground=ACCENT_HOV, activeforeground=BG,
            relief="flat", bd=0, font=FONT_BOLD,
            padx=14, pady=5, cursor="hand2",
            command=lambda: self._switch_scene(SCENE_SOLAR))
        self._btn_solar.pack(side="left")

        self._scene_hint = tk.Label(scene_bar, bg=PANEL, fg=TEXT_DIM, font=FONT_SMALL,
                                    text="Toggle shapes below")
        self._scene_hint.pack(side="left", padx=12)

        # ── Shape panel ────────────────────────────────────────────────────
        self._shape_panel = tk.Frame(self.root, bg=PANEL, padx=10, pady=8)
        self._shape_panel.pack(fill="x", padx=0, pady=(1, 0))

        tk.Label(self._shape_panel, text="SCENE OBJECTS", bg=PANEL, fg=TEXT_DIM,
                 font=("Helvetica", 8, "bold")).grid(
                     row=0, column=0, columnspan=6, sticky="w", pady=(0, 4))

        self._checkboxes = []
        for i, ((label, _), var) in enumerate(zip(SHAPES_BASIC, self.shape_vars)):
            cb = make_check(self._shape_panel, label, var, command=self._render)
            cb.grid(row=1, column=i, padx=6, pady=2, sticky="w")
            self._checkboxes.append(cb)

        self._solar_desc = tk.Label(
            self._shape_panel,
            text="Solar panel · floor · walls · ceiling · table · chair · lamp · bookshelf",
            bg=PANEL, fg=TEXT_DIM, font=FONT_SMALL)

        separator(self.root)

        # ── Main content ───────────────────────────────────────────────────
        content = tk.Frame(self.root, bg=BG)
        content.pack(fill="both", padx=10, pady=(0, 6))

        # Render canvas
        canvas_frame = tk.Frame(content, bg=BG)
        canvas_frame.pack(side="left")
        tk.Label(canvas_frame, text="RENDER OUTPUT", bg=BG, fg=TEXT_DIM,
                 font=("Helvetica", 8, "bold")).pack(anchor="w", pady=(0, 2))
        self.canvas = tk.Canvas(canvas_frame, width=400, height=400,
                                bg=CANVAS_BG, highlightthickness=1,
                                highlightbackground=BORDER)
        self.canvas.pack()

        # Sidebar
        sidebar = tk.Frame(content, bg=BG, padx=14)
        sidebar.pack(side="left", fill="both", expand=True)

        # Actions
        tk.Label(sidebar, text="ACTIONS", bg=BG, fg=TEXT_DIM,
                 font=("Helvetica", 8, "bold")).pack(anchor="w")
        btn_frame = tk.Frame(sidebar, bg=BG)
        btn_frame.pack(fill="x", pady=(4, 8))
        make_btn(btn_frame, "↺  Re-render", self._render).pack(fill="x", pady=2)
        make_btn(btn_frame, "⌫  Delete Left Half (BVH demo)",
                 self._delete_demo, color=DANGER, hover=DANGER_HOV,
                 font=FONT_UI).pack(fill="x", pady=2)

        separator(sidebar)

        # Overview map
        tk.Label(sidebar, text="LIGHT POSITION  (top-down X–Z view)",
                 bg=BG, fg=TEXT_DIM, font=("Helvetica", 8, "bold")).pack(anchor="w")
        tk.Label(sidebar, text="halo size ∝ height (Y-axis)",
                 bg=BG, fg=TEXT_DIM, font=("Helvetica", 7)).pack(anchor="w")
        self.overview = OverviewCanvas(sidebar)
        self.overview.pack(pady=(4, 8))

        separator(sidebar)

        # ── Light controls ─────────────────────────────────────────────────
        tk.Label(sidebar, text="MOVE LIGHT SOURCE  (hold to keep moving)",
                 bg=BG, fg=TEXT_DIM,
                 font=("Helvetica", 8, "bold")).pack(anchor="w", pady=(0, 4))

        ctrl_outer = tk.Frame(sidebar, bg=BG)
        ctrl_outer.pack()
        dpad = tk.Frame(ctrl_outer, bg=BG)
        dpad.pack(side="left")

        def make_arrow(parent, text, fn, row, col):
            b = tk.Button(parent, text=text,
                          bg=BTN_BG, fg=BTN_FG,
                          activebackground=BTN_HOV_BG, activeforeground=BTN_HOV_FG,
                          relief="flat", bd=0, font=FONT_ARROW,
                          width=3, height=1, cursor="hand2")
            b.bind("<Enter>", lambda e: b.config(bg=BTN_HOV_BG, fg=BTN_HOV_FG))
            b.bind("<Leave>", lambda e: b.config(bg=BTN_BG,     fg=BTN_FG))
            b.grid(row=row, column=col, padx=2, pady=2, sticky="nsew")
            bind_hold_repeat(b, fn, self.root)
            return b

        make_arrow(dpad, "↑", lambda: self._move_light(0,  1,  0), 0, 1)
        make_arrow(dpad, "←", lambda: self._move_light(-1, 0,  0), 1, 0)

        # Centre dot re-renders without moving
        center = tk.Button(dpad, text="·", command=self._render,
                           bg=BTN_BG, fg=BTN_FG,
                           activebackground=BTN_HOV_BG, activeforeground=BTN_HOV_FG,
                           relief="flat", bd=0, font=FONT_ARROW,
                           width=3, height=1, cursor="hand2")
        center.bind("<Enter>", lambda e: center.config(bg=BTN_HOV_BG, fg=BTN_HOV_FG))
        center.bind("<Leave>", lambda e: center.config(bg=BTN_BG,     fg=BTN_FG))
        center.grid(row=1, column=1, padx=2, pady=2, sticky="nsew")

        make_arrow(dpad, "→", lambda: self._move_light( 1, 0,  0), 1, 2)
        make_arrow(dpad, "↓", lambda: self._move_light(0, -1,  0), 2, 1)

        # Z-axis
        zdep = tk.Frame(ctrl_outer, bg=BG, padx=8)
        zdep.pack(side="left", fill="y")
        tk.Label(zdep, text="Z-axis", bg=BG, fg=TEXT_DIM, font=FONT_SMALL).pack()

        def make_z(text, fn):
            b = tk.Button(zdep, text=text,
                          bg=BTN_BG, fg=BTN_FG,
                          activebackground=BTN_HOV_BG, activeforeground=BTN_HOV_FG,
                          relief="flat", bd=0, font=FONT_UI,
                          cursor="hand2", padx=8, pady=6)
            b.bind("<Enter>", lambda e: b.config(bg=BTN_HOV_BG, fg=BTN_HOV_FG))
            b.bind("<Leave>", lambda e: b.config(bg=BTN_BG,     fg=BTN_FG))
            b.pack(fill="x", pady=2)
            bind_hold_repeat(b, fn, self.root)
            return b

        make_z("⬆ closer",  lambda: self._move_light(0, 0,  1))
        make_z("⬇ farther", lambda: self._move_light(0, 0, -1))

        separator(sidebar)

        # ── Stats panel ────────────────────────────────────────────────────
        tk.Label(sidebar, text="STATS", bg=BG, fg=TEXT_DIM,
                 font=("Helvetica", 8, "bold")).pack(anchor="w", pady=(0, 4))

        stats_frame = tk.Frame(sidebar, bg=BG)
        stats_frame.pack(fill="x")

        self.lightpos_var = tk.StringVar(value="—")
        self.exposure_var = tk.StringVar(value="—")
        self.bvh_var      = tk.StringVar(value="—")
        self.bvh_exp_var  = tk.StringVar(value="—")

        def stat_row(label, var, value_color=TEXT_CODE):
            row = tk.Frame(stats_frame, bg=BG)
            row.pack(fill="x", pady=2)
            tk.Label(row, text=label, bg=BG, fg=TEXT_DIM,
                     font=FONT_MONO, width=20, anchor="w").pack(side="left")
            tk.Label(row, textvariable=var, bg=BG, fg=value_color,
                     font=FONT_MONO_B, anchor="w").pack(side="left")

        stat_row("Light pos :",    self.lightpos_var, ACCENT)
        stat_row("Solar exposure:", self.exposure_var, LIGHT_CLR)
        stat_row("BVH (render) :", self.bvh_var)
        stat_row("BVH (exposure):", self.bvh_exp_var)

        # Panel absorption row — only shown in solar mode
        self._panel_row = tk.Frame(stats_frame, bg=BG)
        tk.Label(self._panel_row, text="Panel absorb :", bg=BG, fg=TEXT_DIM,
                 font=FONT_MONO, width=20, anchor="w").pack(side="left")
        self.panel_abs_var = tk.StringVar(value="—")
        tk.Label(self._panel_row, textvariable=self.panel_abs_var,
                 bg=BG, fg="#5be0ff", font=FONT_MONO_B, anchor="w").pack(side="left")

        # ── Status bar ─────────────────────────────────────────────────────
        separator(self.root, pad=0)
        status_bar = tk.Frame(self.root, bg=PANEL, pady=4)
        status_bar.pack(fill="x")
        tk.Label(status_bar, textvariable=self._status_var,
                 bg=PANEL, fg=TEXT_DIM, font=FONT_SMALL,
                 padx=10, anchor="w").pack(side="left")

    # -----------------------------------------------------------------------
    # Scene switching
    # -----------------------------------------------------------------------

    def _switch_scene(self, mode):
        if mode == self._scene_mode:
            return
        self._scene_mode = mode

        if mode == SCENE_BASIC:
            self._btn_basic.config(bg=ACCENT,  fg=BG)
            self._btn_solar.config(bg=BTN_BG,  fg=BTN_FG)
            self._scene_hint.config(text="Toggle shapes below")
            # Show checkboxes, hide solar description + panel row
            self._solar_desc.grid_remove()
            for i, cb in enumerate(self._checkboxes):
                cb.grid(row=1, column=i, padx=6, pady=2, sticky="w")
            self._panel_row.pack_forget()
        else:
            self._btn_solar.config(bg=ACCENT,  fg=BG)
            self._btn_basic.config(bg=BTN_BG,  fg=BTN_FG)
            self._scene_hint.config(text="Absorption measured on panel surface")
            # Hide checkboxes, show solar description + panel row
            for cb in self._checkboxes:
                cb.grid_remove()
            self._solar_desc.grid(row=1, column=0, columnspan=6,
                                  sticky="w", pady=2)
            self._panel_row.pack(fill="x", pady=2)

        self._render()

    # -----------------------------------------------------------------------
    # Actions
    # -----------------------------------------------------------------------

    def _move_light(self, dx, dy, dz):
        self.light[0] += dx * LIGHT_STEP
        self.light[1] += dy * LIGHT_STEP
        self.light[2] += dz * LIGHT_STEP
        self._status_var.set(
            f"Light → ({self.light[0]:+.1f}, {self.light[1]:+.1f}, "
            f"{self.light[2]:+.1f})  |  rendering…")
        self.root.update_idletasks()
        self._render()

    def _selected_shape_lines(self):
        if self._scene_mode == SCENE_BASIC:
            return [line for (_, line), v in zip(SHAPES_BASIC, self.shape_vars)
                    if v.get()]
        return [line for (_, line) in SHAPES_SOLAR]

    def _render(self, delete_region=None):
        shapes = self._selected_shape_lines()
        write_scene(self.light, shapes)
        self._status_var.set("Rendering…")
        self.root.update_idletasks()
        try:
            stats = run_raytracer(delete_region=delete_region)
        except Exception as e:
            messagebox.showerror("Raytracer error", str(e))
            self._status_var.set("Render failed — see error dialog.")
            return
        self._show_image(OUTPUT_PPM)
        self._update_stats(stats)
        self.overview.draw_shapes(
            self._scene_mode,
            self.shape_vars if self._scene_mode == SCENE_BASIC else None)
        self.overview.update_light(*self.light)
        self._status_var.set("Render complete.")

    def _delete_demo(self):
        self._render(delete_region=[-10, -10, -10, 0, 10, 10])
        messagebox.showinfo(
            "BVH Region Delete",
            "BVHNode::remove_region was called on the left half of the scene "
            "(x ≤ 0) BEFORE rendering.\n\n"
            "The BVH skipped entire right-side subtrees whose AABBs don't "
            "overlap the region — O(K + log n) instead of O(n).\n\n"
            "Uncheck shapes in the top bar to remove them permanently.")

    def _show_image(self, ppm_path):
        if not Path(ppm_path).exists():
            return
        self.photo = load_ppm_as_photoimage(ppm_path)
        self.canvas.delete("all")
        self.canvas.create_image(0, 0, anchor="nw", image=self.photo)

    def _update_stats(self, stats):
        # ── Light position ─────────────────────────────────────────────────
        lx, ly, lz = self.light
        self.lightpos_var.set(f"({lx:+.1f}, {ly:+.1f}, {lz:+.1f})")

        # ── Solar exposure (fraction of floor lit) ─────────────────────────
        if "EXPOSURE" in stats:
            pct = float(stats["EXPOSURE"]) * 100
            self.exposure_var.set(f"{pct:.1f}%  of floor lit")
        else:
            self.exposure_var.set("—")

        # ── BVH render stats ───────────────────────────────────────────────
        prunes  = stats.get("BVH_PRUNES", "?")
        leaves  = stats.get("BVH_LEAVES_TESTED", "?")
        removed = stats.get("REMOVED")
        rt = f"{int(prunes):,} prunes  /  {int(leaves):,} leaf tests"
        if removed:
            rt += f"  [{removed} removed]"
        self.bvh_var.set(rt)

        # ── BVH exposure stats ─────────────────────────────────────────────
        ep = stats.get("EXPOSURE_BVH_PRUNES", "?")
        el = stats.get("EXPOSURE_BVH_LEAVES", "?")
        self.bvh_exp_var.set(f"{int(ep):,} prunes  /  {int(el):,} leaf tests")

        # ── Panel absorption────────────────────────────
        if self._scene_mode == SCENE_SOLAR:

            # compute_exposure in World.cpp samples at floor_y=-5 by default.
            # The solar panel is at y=-2 (3 units above the floor cuz meh why not)
            # Factor = (dist_to_floor / dist_to_panel)^2 clamped to [0,1].
            

            if "EXPOSURE" in stats:
                floor_y  = -5.0
                panel_y  = -2.0
                light_y  = self.light[1]
                # vertical distances
                dist_fl = abs(light_y - floor_y)
                dist_pa = abs(light_y - panel_y)
                if dist_pa > 0:
                    scale = min(1.0, (dist_fl / dist_pa) ** 2)
                else:
                    scale = 1.0
                base_pct  = float(stats["EXPOSURE"])
                panel_pct = min(1.0, base_pct * scale) * 100
                self.panel_abs_var.set(f"{panel_pct:.1f}%  panel surface lit")
            else:
                self.panel_abs_var.set("—")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    if not RAYTRACER.exists():
        print(f"ERROR: raytracer binary not found at {RAYTRACER}")
        print("Build with build.sh first.")
        return 1
    root = tk.Tk()
    App(root)
    root.mainloop()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
